import type {
  Faq,
  FuelRates,
  PricingRules,
  Route,
  Service,
  Testimonial,
  Vehicle,
} from "./types";

/**
 * Preview data.
 *
 * Every number here is a stand-in so the interface can be built and reviewed
 * before the real fleet and rate card arrive. None of it is real pricing.
 * The ribbon rendered by PreviewDataNotice makes that visible on screen, and it
 * disappears automatically once NEXT_PUBLIC_DATA_SOURCE is set to "cms".
 */

const noModel = { accuracy: "none", glbUrl: null, attribution: null } as const;

export const vehicles: Vehicle[] = [
  {
    id: "v-yaris-ativ-x",
    slug: "toyota-yaris-ativ-x",
    make: "Toyota",
    model: "Yaris",
    variant: "ATIV X 1.5 CVT",
    year: 2023,
    category: "sedan",
    specs: {
      engineCc: 1496,
      seats: 5,
      doors: 4,
      luggage: 2,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 12,
      mileageHighwayKmpl: 16,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 9000,
      withoutFuelDaily: 6500,
      outOfCityDaily: 11000,
      perKm: 35,
      overtimePerHour: 500,
      driverAllowance: 1500,
      nightStayCharge: 1500,
      securityDeposit: 25000,
    },
    colors: [
      { name: "Super White", hex: "#F2F3F5" },
      { name: "Attitude Black", hex: "#17181A" },
      { name: "Silver Metallic", hex: "#B9BCC0" },
      { name: "Red Mica", hex: "#9E2B2B" },
    ],
    images: [],
    features: [
      "Cruise control",
      "Push start",
      "Rear camera",
      "Automatic climate control",
    ],
    model3d: noModel,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-city-aspire",
    slug: "honda-city-aspire",
    make: "Honda",
    model: "City",
    variant: "Aspire 1.5 CVT",
    year: 2023,
    category: "sedan",
    specs: {
      engineCc: 1498,
      seats: 5,
      doors: 4,
      luggage: 2,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 12,
      mileageHighwayKmpl: 16,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 9500,
      withoutFuelDaily: 7000,
      outOfCityDaily: 11500,
      perKm: 36,
      overtimePerHour: 500,
      driverAllowance: 1500,
      nightStayCharge: 1500,
      securityDeposit: 25000,
    },
    colors: [
      { name: "Taffeta White", hex: "#F4F5F6" },
      { name: "Crystal Black", hex: "#14151A" },
      { name: "Lunar Silver", hex: "#AEB2B6" },
    ],
    images: [],
    features: ["LaneWatch camera", "Paddle shifters", "Keyless entry"],
    model3d: noModel,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-civic-oriel",
    slug: "honda-civic-oriel",
    make: "Honda",
    model: "Civic",
    variant: "Oriel 1.5 Turbo",
    year: 2023,
    category: "luxury",
    specs: {
      engineCc: 1498,
      seats: 5,
      doors: 4,
      luggage: 3,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 10,
      mileageHighwayKmpl: 14,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 15000,
      withoutFuelDaily: 11000,
      outOfCityDaily: 18000,
      perKm: 48,
      overtimePerHour: 800,
      driverAllowance: 2000,
      nightStayCharge: 2000,
      securityDeposit: 50000,
    },
    colors: [
      { name: "Platinum White", hex: "#F6F6F4" },
      { name: "Crystal Black", hex: "#131417" },
      { name: "Meteoroid Grey", hex: "#55585C" },
    ],
    images: [],
    features: ["Sunroof", "Leather seats", "Honda Sensing", "Wireless charging"],
    model3d: noModel,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-corolla-grande",
    slug: "toyota-corolla-altis-grande",
    make: "Toyota",
    model: "Corolla",
    variant: "Altis Grande 1.8",
    year: 2023,
    category: "sedan",
    specs: {
      engineCc: 1798,
      seats: 5,
      doors: 4,
      luggage: 3,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 11,
      mileageHighwayKmpl: 15,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 12000,
      withoutFuelDaily: 9000,
      outOfCityDaily: 15000,
      perKm: 42,
      overtimePerHour: 700,
      driverAllowance: 1800,
      nightStayCharge: 1800,
      securityDeposit: 40000,
    },
    colors: [
      { name: "Super White", hex: "#F3F4F5" },
      { name: "Attitude Black", hex: "#16171A" },
      { name: "Phantom Brown", hex: "#5A4A42" },
    ],
    images: [],
    features: ["Cruise control", "Dual zone climate", "Rear camera"],
    model3d: noModel,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-alto-vxl",
    slug: "suzuki-alto-vxl-ags",
    make: "Suzuki",
    model: "Alto",
    variant: "VXL AGS",
    year: 2023,
    category: "economy",
    specs: {
      engineCc: 660,
      seats: 4,
      doors: 4,
      luggage: 1,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 18,
      mileageHighwayKmpl: 22,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 6000,
      withoutFuelDaily: 4500,
      outOfCityDaily: 7500,
      perKm: 24,
      overtimePerHour: 350,
      driverAllowance: 1500,
      nightStayCharge: 1500,
      securityDeposit: 15000,
    },
    colors: [
      { name: "Pearl White", hex: "#F1F2F2" },
      { name: "Graphite Grey", hex: "#4B4E52" },
      { name: "Solid Black", hex: "#18191B" },
    ],
    images: [],
    features: ["Power steering", "Air conditioning", "Airbags"],
    model3d: noModel,
    availableForCorporate: false,
    isFeatured: false,
  },
  {
    id: "v-cultus-vxl",
    slug: "suzuki-cultus-vxl",
    make: "Suzuki",
    model: "Cultus",
    variant: "VXL",
    year: 2022,
    category: "economy",
    specs: {
      engineCc: 998,
      seats: 5,
      doors: 4,
      luggage: 2,
      transmission: "manual",
      fuelType: "petrol",
      mileageCityKmpl: 14,
      mileageHighwayKmpl: 18,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 7000,
      withoutFuelDaily: 5000,
      outOfCityDaily: 8500,
      perKm: 28,
      overtimePerHour: 400,
      driverAllowance: 1500,
      nightStayCharge: 1500,
      securityDeposit: 20000,
    },
    colors: [
      { name: "Pearl White", hex: "#F1F2F2" },
      { name: "Silky Silver", hex: "#B3B6BA" },
    ],
    images: [],
    features: ["Touchscreen", "Rear camera", "Airbags"],
    model3d: noModel,
    availableForCorporate: false,
    isFeatured: false,
  },
  {
    id: "v-sportage-alpha",
    slug: "kia-sportage-alpha",
    make: "Kia",
    model: "Sportage",
    variant: "Alpha",
    year: 2023,
    category: "suv",
    specs: {
      engineCc: 1999,
      seats: 5,
      doors: 5,
      luggage: 4,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 9,
      mileageHighwayKmpl: 13,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 18000,
      withoutFuelDaily: 13500,
      outOfCityDaily: 22000,
      perKm: 60,
      overtimePerHour: 1000,
      driverAllowance: 2000,
      nightStayCharge: 2000,
      securityDeposit: 60000,
    },
    colors: [
      { name: "Clear White", hex: "#F5F6F6" },
      { name: "Aurora Black", hex: "#131416" },
      { name: "Steel Grey", hex: "#60646A" },
    ],
    images: [],
    features: ["Panoramic roof", "Ventilated seats", "360 camera"],
    model3d: noModel,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-fortuner-legender",
    slug: "toyota-fortuner-legender",
    make: "Toyota",
    model: "Fortuner",
    variant: "Legender 2.8 4x4",
    year: 2023,
    category: "luxury",
    specs: {
      engineCc: 2755,
      seats: 7,
      doors: 5,
      luggage: 4,
      transmission: "automatic",
      fuelType: "diesel",
      mileageCityKmpl: 8,
      mileageHighwayKmpl: 12,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 30000,
      withoutFuelDaily: 24000,
      outOfCityDaily: 35000,
      perKm: 95,
      overtimePerHour: 1500,
      driverAllowance: 2500,
      nightStayCharge: 2500,
      securityDeposit: 100000,
    },
    colors: [
      { name: "Attitude Black", hex: "#141518" },
      { name: "Super White", hex: "#F4F5F6" },
      { name: "Phantom Brown", hex: "#574840" },
    ],
    images: [],
    features: ["4x4", "Leather interior", "Power tailgate", "JBL audio"],
    model3d: noModel,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-hiace-grand-cabin",
    slug: "toyota-hiace-grand-cabin",
    make: "Toyota",
    model: "Hiace",
    variant: "Grand Cabin",
    year: 2022,
    category: "van",
    specs: {
      engineCc: 2694,
      seats: 13,
      doors: 4,
      luggage: 6,
      transmission: "manual",
      fuelType: "petrol",
      mileageCityKmpl: 7,
      mileageHighwayKmpl: 10,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 22000,
      withoutFuelDaily: 16000,
      outOfCityDaily: 26000,
      perKm: 85,
      overtimePerHour: 1200,
      driverAllowance: 2500,
      nightStayCharge: 2500,
      securityDeposit: 50000,
    },
    colors: [{ name: "Super White", hex: "#F3F4F5" }],
    images: [],
    features: ["Dual air conditioning", "Reclining seats", "Luggage space"],
    model3d: noModel,
    availableForCorporate: true,
    isFeatured: false,
  },
  {
    id: "v-coaster",
    slug: "toyota-coaster",
    make: "Toyota",
    model: "Coaster",
    variant: "22 Seater",
    year: 2021,
    category: "coaster",
    specs: {
      engineCc: 4164,
      seats: 22,
      doors: 2,
      luggage: 10,
      transmission: "manual",
      fuelType: "diesel",
      mileageCityKmpl: 5,
      mileageHighwayKmpl: 8,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 35000,
      withoutFuelDaily: 26000,
      outOfCityDaily: 42000,
      perKm: 130,
      overtimePerHour: 1800,
      driverAllowance: 3000,
      nightStayCharge: 3000,
      securityDeposit: 75000,
    },
    colors: [{ name: "Super White", hex: "#F3F4F5" }],
    images: [],
    features: ["22 seats", "Air conditioning", "Public address system"],
    model3d: noModel,
    availableForCorporate: true,
    isFeatured: false,
  },
];

export const fuelRates: FuelRates = {
  petrol: 264.61,
  diesel: 272.77,
  hiOctane: 289.5,
  effectiveFrom: "2026-10-01",
  note: "Preview values. Replace with the current notified rates before launch.",
};

export const pricingRules: PricingRules = {
  marginPercent: 10,
  withoutFuelAdjustPercent: 0,
  defaultDriverAllowance: 1500,
  nightStayCharge: 1500,
  chargeReturnLegFuel: true,
  includedKmPerDay: 100,
  roundToNearest: 100,
};

export const routes: Route[] = [
  { origin: "Lahore", destination: "Islamabad", distanceKm: 375, estimatedHours: 4.5, tollCharges: 1200 },
  { origin: "Lahore", destination: "Multan", distanceKm: 350, estimatedHours: 4, tollCharges: 1100 },
  { origin: "Lahore", destination: "Faisalabad", distanceKm: 185, estimatedHours: 2.5, tollCharges: 600 },
  { origin: "Lahore", destination: "Karachi", distanceKm: 1210, estimatedHours: 16, tollCharges: 3500 },
  { origin: "Lahore", destination: "Murree", distanceKm: 410, estimatedHours: 5.5, tollCharges: 1400 },
  { origin: "Islamabad", destination: "Murree", distanceKm: 60, estimatedHours: 1.5, tollCharges: 200 },
  { origin: "Islamabad", destination: "Peshawar", distanceKm: 185, estimatedHours: 2, tollCharges: 500 },
  { origin: "Islamabad", destination: "Naran", distanceKm: 270, estimatedHours: 7, tollCharges: 400 },
  { origin: "Karachi", destination: "Hyderabad", distanceKm: 165, estimatedHours: 2, tollCharges: 400 },
];

export const services: Service[] = [
  {
    id: "s-daily",
    slug: "daily-rental",
    title: "Daily Rental",
    summary:
      "Any vehicle in the fleet by the day, with or without a driver, inside the city or on the road.",
    icon: "calendar",
  },
  {
    id: "s-corporate",
    slug: "corporate-fleet",
    title: "Corporate Fleet Leasing",
    summary:
      "Long-term contracts with vetted drivers, scheduled maintenance and a replacement vehicle guarantee.",
    icon: "briefcase",
  },
  {
    id: "s-airport",
    slug: "airport-transfer",
    title: "Airport Transfer",
    summary:
      "Fixed-price pick-up and drop-off with flight tracking, so a delayed landing costs nothing extra.",
    icon: "plane",
  },
  {
    id: "s-intercity",
    slug: "intercity-travel",
    title: "Intercity Travel",
    summary:
      "Point-to-point journeys priced on distance and the day's fuel rate, quoted before you commit.",
    icon: "route",
  },
  {
    id: "s-events",
    slug: "wedding-and-events",
    title: "Wedding and Events",
    summary: "Presentation-ready vehicles with experienced drivers for events.",
    icon: "sparkles",
  },
  {
    id: "s-staff",
    slug: "staff-transport",
    title: "Staff Transport",
    summary:
      "Scheduled pick and drop for teams, billed monthly against a single invoice.",
    icon: "users",
  },
];

export const faqs: Faq[] = [
  {
    id: "f-documents",
    question: "What documents do I need to rent a car?",
    answer:
      "A valid CNIC and a driving licence for self-drive rentals. Corporate accounts are opened against company registration documents. Exact requirements are confirmed at booking.",
  },
  {
    id: "f-fuel",
    question: "What is the difference between the with-fuel and without-fuel rate?",
    answer:
      "The with-fuel rate includes the fuel for your trip, calculated from the distance, the vehicle's consumption and the day's fuel price. The without-fuel rate covers the vehicle alone and you fill it yourself.",
  },
  {
    id: "f-estimate",
    question: "Why does the fare estimate change from day to day?",
    answer:
      "Fuel prices in Pakistan are revised regularly. Every with-fuel quote is calculated against the current rate, which is published on our fuel prices page along with the date it took effect.",
  },
  {
    id: "f-driver",
    question: "Can I rent without a driver?",
    answer:
      "Yes. Self-drive is available on most of the fleet, subject to documents and a security deposit. Some premium vehicles are chauffeur-driven only.",
  },
  {
    id: "f-cities",
    question: "Which cities do you operate in?",
    answer:
      "Vehicles can be collected in our listed pick-up cities, and out-of-station travel is available nationwide.",
  },
];

/**
 * Testimonials are intentionally empty.
 *
 * Only genuine reviews are published. Fabricated reviews carry a Google policy
 * penalty that removes the entire site from search results, which would defeat
 * the purpose of the build. The components are ready and the section appears as
 * soon as real reviews are supplied.
 */
export const testimonials: Testimonial[] = [];
