import type {
  Faq,
  FuelRateRecord,
  FuelRates,
  PricingRules,
  Route,
  Service,
  Testimonial,
  Vehicle,
} from "./types";

/**
 * The fleet, taken from the vehicle register supplied by the business:
 * 81 vehicles across 20 models. Each entry carries how many of that model are
 * on the road, so the site never implies a larger fleet than exists.
 *
 * Specifications are indicative and rates are placeholders until the rate card
 * arrives. The ribbon rendered by PreviewDataNotice says so on every page, and
 * it disappears once NEXT_PUBLIC_DATA_SOURCE is set to "cms".
 *
 * model3d is null on every vehicle until a Sketchfab model has been chosen for
 * it; the viewer falls back to the photo gallery, so an empty field never
 * leaves a hole in the page.
 */

export const vehicles: Vehicle[] = [
  {
    id: "v-toyota-coaster",
    slug: "toyota-coaster",
    make: "Toyota",
    model: "Coaster",
    variant: "22 Seater",
    year: 2025,
    category: "coaster",
    unitsInFleet: 22,
    specs: {
      engineCc: 4164,
      seats: 22,
      doors: 2,
      luggage: 10,
      transmission: "manual",
      fuelType: "diesel",
      mileageCityKmpl: 5,
      mileageHighwayKmpl: 8,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 35000,
      withoutFuelDaily: 26000,
      outOfCityDaily: 42000,
      perKm: 130,
      overtimePerHour: 1800,
      driverAllowance: 3000,
      nightStayCharge: 3000,
      securityDeposit: 75000,
    },
    colors: [
      { name: "Super White", hex: "#F3F4F5" },
    ],
    images: [],
    features: [
      "22 reclining seats",
      "Dual air conditioning",
      "Public address system",
      "Overhead luggage racks",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-toyota-hiace",
    slug: "toyota-hiace",
    make: "Toyota",
    model: "Hiace",
    variant: "Grand Cabin",
    year: 2025,
    category: "van",
    unitsInFleet: 21,
    specs: {
      engineCc: 2694,
      seats: 13,
      doors: 4,
      luggage: 6,
      transmission: "manual",
      fuelType: "petrol",
      mileageCityKmpl: 7,
      mileageHighwayKmpl: 10,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 22000,
      withoutFuelDaily: 16000,
      outOfCityDaily: 26000,
      perKm: 85,
      overtimePerHour: 1200,
      driverAllowance: 2500,
      nightStayCharge: 2500,
      securityDeposit: 50000,
    },
    colors: [
      { name: "Super White", hex: "#F3F4F5" },
      { name: "Silver Metallic", hex: "#B9BCC0" },
    ],
    images: [],
    features: [
      "13 reclining seats",
      "Dual air conditioning",
      "Tinted glass",
      "Luggage space",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-daewoo-bus-116",
    slug: "daewoo-bus-116",
    make: "Daewoo",
    model: "BUS-116",
    variant: "Intercity Coach",
    year: 2022,
    category: "bus",
    unitsInFleet: 5,
    specs: {
      engineCc: 8000,
      seats: 45,
      doors: 2,
      luggage: 20,
      transmission: "manual",
      fuelType: "diesel",
      mileageCityKmpl: 3,
      mileageHighwayKmpl: 5,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 55000,
      withoutFuelDaily: 42000,
      outOfCityDaily: 65000,
      perKm: 190,
      overtimePerHour: 2500,
      driverAllowance: 3500,
      nightStayCharge: 3500,
      securityDeposit: 120000,
    },
    colors: [
      { name: "White", hex: "#F2F3F5" },
    ],
    images: [],
    features: [
      "45 seats",
      "Air conditioning",
      "Reclining seats",
      "Large luggage hold",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-changan-karvaan-plus",
    slug: "changan-karvaan-plus",
    make: "Changan",
    model: "Karvaan Plus",
    variant: "7 Seater",
    year: 2025,
    category: "van",
    unitsInFleet: 4,
    specs: {
      engineCc: 1000,
      seats: 7,
      doors: 5,
      luggage: 3,
      transmission: "manual",
      fuelType: "petrol",
      mileageCityKmpl: 11,
      mileageHighwayKmpl: 14,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 10000,
      withoutFuelDaily: 7500,
      outOfCityDaily: 12500,
      perKm: 38,
      overtimePerHour: 600,
      driverAllowance: 1500,
      nightStayCharge: 1500,
      securityDeposit: 25000,
    },
    colors: [
      { name: "White", hex: "#F2F3F5" },
      { name: "Silver", hex: "#B6B9BE" },
    ],
    images: [],
    features: [
      "7 seats",
      "Air conditioning",
      "Flexible seating",
      "Economical running",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: false,
  },
  {
    id: "v-toyota-corolla-altis",
    slug: "toyota-corolla-altis",
    make: "Toyota",
    model: "Corolla",
    variant: "Altis 1.6",
    year: 2026,
    category: "sedan",
    unitsInFleet: 4,
    specs: {
      engineCc: 1598,
      seats: 5,
      doors: 4,
      luggage: 3,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 11,
      mileageHighwayKmpl: 15,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 12000,
      withoutFuelDaily: 9000,
      outOfCityDaily: 15000,
      perKm: 42,
      overtimePerHour: 700,
      driverAllowance: 1800,
      nightStayCharge: 1800,
      securityDeposit: 40000,
    },
    colors: [
      { name: "Super White", hex: "#F3F4F5" },
      { name: "Attitude Black", hex: "#16171A" },
      { name: "Silver Metallic", hex: "#B9BCC0" },
      { name: "Phantom Brown", hex: "#5A4A42" },
    ],
    images: [],
    features: [
      "Cruise control",
      "Dual zone climate",
      "Rear camera",
      "Push start",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-toyota-prado-txl",
    slug: "toyota-prado-txl",
    make: "Toyota",
    model: "Prado",
    variant: "TXL",
    year: 2021,
    category: "luxury",
    unitsInFleet: 3,
    specs: {
      engineCc: 2982,
      seats: 7,
      doors: 5,
      luggage: 5,
      transmission: "automatic",
      fuelType: "diesel",
      mileageCityKmpl: 7,
      mileageHighwayKmpl: 10,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 33000,
      withoutFuelDaily: 26000,
      outOfCityDaily: 38000,
      perKm: 105,
      overtimePerHour: 1600,
      driverAllowance: 2500,
      nightStayCharge: 2500,
      securityDeposit: 100000,
    },
    colors: [
      { name: "Pearl White", hex: "#F1F2F3" },
      { name: "Attitude Black", hex: "#15161A" },
      { name: "Silver", hex: "#B4B7BC" },
    ],
    images: [],
    features: [
      "4x4",
      "Leather interior",
      "Sunroof",
      "Seven seats",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-toyota-land-cruiser-axg",
    slug: "toyota-land-cruiser-axg",
    make: "Toyota",
    model: "Land Cruiser",
    variant: "AXG",
    year: 2012,
    category: "luxury",
    unitsInFleet: 3,
    specs: {
      engineCc: 4608,
      seats: 7,
      doors: 5,
      luggage: 6,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 5,
      mileageHighwayKmpl: 8,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 40000,
      withoutFuelDaily: 32000,
      outOfCityDaily: 46000,
      perKm: 135,
      overtimePerHour: 2000,
      driverAllowance: 3000,
      nightStayCharge: 3000,
      securityDeposit: 150000,
    },
    colors: [
      { name: "Pearl White", hex: "#F2F3F4" },
      { name: "Black", hex: "#141518" },
    ],
    images: [],
    features: [
      "4x4",
      "Leather interior",
      "Rear entertainment",
      "Seven seats",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-gwm-haval-h6-hev",
    slug: "gwm-haval-h6-hev",
    make: "GWM Haval",
    model: "H6",
    variant: "HEV",
    year: 2026,
    category: "suv",
    unitsInFleet: 2,
    specs: {
      engineCc: 1497,
      seats: 5,
      doors: 5,
      luggage: 4,
      transmission: "automatic",
      fuelType: "hybrid",
      mileageCityKmpl: 14,
      mileageHighwayKmpl: 17,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 20000,
      withoutFuelDaily: 15000,
      outOfCityDaily: 24000,
      perKm: 66,
      overtimePerHour: 1100,
      driverAllowance: 2000,
      nightStayCharge: 2000,
      securityDeposit: 70000,
    },
    colors: [
      { name: "Hamilton White", hex: "#F3F4F6" },
      { name: "Golden Black", hex: "#17181B" },
      { name: "Energy Green", hex: "#2E4A3C" },
    ],
    images: [],
    features: [
      "Hybrid drivetrain",
      "Panoramic roof",
      "360 camera",
      "Ventilated seats",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-honda-civic-oriel",
    slug: "honda-civic-oriel",
    make: "Honda",
    model: "Civic",
    variant: "Oriel",
    year: 2022,
    category: "sedan",
    unitsInFleet: 2,
    specs: {
      engineCc: 1498,
      seats: 5,
      doors: 4,
      luggage: 3,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 10,
      mileageHighwayKmpl: 14,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 15000,
      withoutFuelDaily: 11000,
      outOfCityDaily: 18000,
      perKm: 48,
      overtimePerHour: 800,
      driverAllowance: 2000,
      nightStayCharge: 2000,
      securityDeposit: 50000,
    },
    colors: [
      { name: "Platinum White", hex: "#F6F6F4" },
      { name: "Crystal Black", hex: "#131417" },
      { name: "Meteoroid Grey", hex: "#55585C" },
    ],
    images: [],
    features: [
      "Sunroof",
      "Leather seats",
      "Honda Sensing",
      "Wireless charging",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-toyota-fortuner-g",
    slug: "toyota-fortuner-g",
    make: "Toyota",
    model: "Fortuner",
    variant: "G",
    year: 2024,
    category: "suv",
    unitsInFleet: 2,
    specs: {
      engineCc: 2694,
      seats: 7,
      doors: 5,
      luggage: 4,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 8,
      mileageHighwayKmpl: 12,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 28000,
      withoutFuelDaily: 22000,
      outOfCityDaily: 33000,
      perKm: 95,
      overtimePerHour: 1500,
      driverAllowance: 2500,
      nightStayCharge: 2500,
      securityDeposit: 100000,
    },
    colors: [
      { name: "Attitude Black", hex: "#141518" },
      { name: "Super White", hex: "#F4F5F6" },
      { name: "Phantom Brown", hex: "#574840" },
    ],
    images: [],
    features: [
      "Seven seats",
      "Leather interior",
      "Power tailgate",
      "Reverse camera",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-toyota-yaris-ativ-x",
    slug: "toyota-yaris-ativ-x",
    make: "Toyota",
    model: "Yaris",
    variant: "ATIV X 1.5",
    year: 2024,
    category: "sedan",
    unitsInFleet: 3,
    specs: {
      engineCc: 1496,
      seats: 5,
      doors: 4,
      luggage: 2,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 12,
      mileageHighwayKmpl: 16,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 9500,
      withoutFuelDaily: 7000,
      outOfCityDaily: 11500,
      perKm: 36,
      overtimePerHour: 500,
      driverAllowance: 1500,
      nightStayCharge: 1500,
      securityDeposit: 25000,
    },
    colors: [
      { name: "Super White", hex: "#F2F3F5" },
      { name: "Attitude Black", hex: "#17181A" },
      { name: "Silver Metallic", hex: "#B9BCC0" },
      { name: "Red Mica", hex: "#9E2B2B" },
    ],
    images: [],
    features: [
      "Cruise control",
      "Push start",
      "Rear camera",
      "Automatic climate control",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-toyota-prado-tx",
    slug: "toyota-prado-tx",
    make: "Toyota",
    model: "Prado",
    variant: "TX",
    year: 2013,
    category: "luxury",
    unitsInFleet: 1,
    specs: {
      engineCc: 2982,
      seats: 7,
      doors: 5,
      luggage: 5,
      transmission: "automatic",
      fuelType: "diesel",
      mileageCityKmpl: 7,
      mileageHighwayKmpl: 10,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 30000,
      withoutFuelDaily: 24000,
      outOfCityDaily: 35000,
      perKm: 98,
      overtimePerHour: 1500,
      driverAllowance: 2500,
      nightStayCharge: 2500,
      securityDeposit: 90000,
    },
    colors: [
      { name: "Pearl White", hex: "#F1F2F3" },
      { name: "Silver", hex: "#B4B7BC" },
    ],
    images: [],
    features: [
      "4x4",
      "Seven seats",
      "Climate control",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: false,
  },
  {
    id: "v-kia-sportage-awd",
    slug: "kia-sportage-awd",
    make: "Kia",
    model: "Sportage",
    variant: "AWD",
    year: 2025,
    category: "suv",
    unitsInFleet: 2,
    specs: {
      engineCc: 1999,
      seats: 5,
      doors: 5,
      luggage: 4,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 9,
      mileageHighwayKmpl: 13,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 18000,
      withoutFuelDaily: 13500,
      outOfCityDaily: 22000,
      perKm: 60,
      overtimePerHour: 1000,
      driverAllowance: 2000,
      nightStayCharge: 2000,
      securityDeposit: 60000,
    },
    colors: [
      { name: "Clear White", hex: "#F5F6F6" },
      { name: "Aurora Black", hex: "#131416" },
      { name: "Steel Grey", hex: "#60646A" },
    ],
    images: [],
    features: [
      "All wheel drive",
      "Panoramic roof",
      "Ventilated seats",
      "360 camera",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: true,
  },
  {
    id: "v-kia-sorento-awd",
    slug: "kia-sorento-awd",
    make: "Kia",
    model: "Sorento",
    variant: "AWD",
    year: 2021,
    category: "suv",
    unitsInFleet: 1,
    specs: {
      engineCc: 2359,
      seats: 7,
      doors: 5,
      luggage: 5,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 8,
      mileageHighwayKmpl: 12,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 22000,
      withoutFuelDaily: 17000,
      outOfCityDaily: 26000,
      perKm: 74,
      overtimePerHour: 1200,
      driverAllowance: 2200,
      nightStayCharge: 2200,
      securityDeposit: 80000,
    },
    colors: [
      { name: "Snow White Pearl", hex: "#F4F5F6" },
      { name: "Aurora Black", hex: "#131416" },
    ],
    images: [],
    features: [
      "Seven seats",
      "All wheel drive",
      "Leather interior",
      "Power tailgate",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: false,
  },
  {
    id: "v-jaecoo-j5-comfort",
    slug: "jaecoo-j5-comfort",
    make: "Jaecoo",
    model: "J5",
    variant: "Comfort",
    year: 2026,
    category: "suv",
    unitsInFleet: 1,
    specs: {
      engineCc: 1498,
      seats: 5,
      doors: 5,
      luggage: 4,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 10,
      mileageHighwayKmpl: 14,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 18000,
      withoutFuelDaily: 13500,
      outOfCityDaily: 22000,
      perKm: 60,
      overtimePerHour: 1000,
      driverAllowance: 2000,
      nightStayCharge: 2000,
      securityDeposit: 60000,
    },
    colors: [
      { name: "Carbon Crystal White", hex: "#F4F5F7" },
      { name: "Mountain Grey", hex: "#6A6E74" },
    ],
    images: [],
    features: [
      "Panoramic roof",
      "Large touchscreen",
      "360 camera",
      "Automatic climate control",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: false,
  },
  {
    id: "v-jac-t9-hunter-4x4",
    slug: "jac-t9-hunter-4x4",
    make: "JAC Motors",
    model: "T9 Hunter",
    variant: "4x4",
    year: 2026,
    category: "pickup",
    unitsInFleet: 1,
    specs: {
      engineCc: 1996,
      seats: 5,
      doors: 4,
      luggage: 5,
      transmission: "automatic",
      fuelType: "diesel",
      mileageCityKmpl: 9,
      mileageHighwayKmpl: 12,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 18000,
      withoutFuelDaily: 14000,
      outOfCityDaily: 22000,
      perKm: 62,
      overtimePerHour: 1000,
      driverAllowance: 2000,
      nightStayCharge: 2000,
      securityDeposit: 70000,
    },
    colors: [
      { name: "Pearl White", hex: "#F3F4F5" },
      { name: "Granite Grey", hex: "#5E6268" },
    ],
    images: [],
    features: [
      "4x4",
      "Double cab",
      "Load bed",
      "Reverse camera",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: false,
  },
  {
    id: "v-toyota-hilux-revo-g",
    slug: "toyota-hilux-revo-g",
    make: "Toyota",
    model: "Hilux",
    variant: "Revo G",
    year: 2017,
    category: "pickup",
    unitsInFleet: 1,
    specs: {
      engineCc: 2755,
      seats: 5,
      doors: 4,
      luggage: 5,
      transmission: "manual",
      fuelType: "diesel",
      mileageCityKmpl: 9,
      mileageHighwayKmpl: 12,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 18000,
      withoutFuelDaily: 14000,
      outOfCityDaily: 22000,
      perKm: 62,
      overtimePerHour: 1000,
      driverAllowance: 2000,
      nightStayCharge: 2000,
      securityDeposit: 60000,
    },
    colors: [
      { name: "Super White", hex: "#F3F4F5" },
      { name: "Silver Metallic", hex: "#B9BCC0" },
    ],
    images: [],
    features: [
      "4x4",
      "Double cab",
      "Load bed",
      "High ground clearance",
    ],
    model3d: null,
    availableForCorporate: true,
    isFeatured: false,
  },
  {
    id: "v-suzuki-wagon-r",
    slug: "suzuki-wagon-r",
    make: "Suzuki",
    model: "Wagon R",
    variant: "VXL",
    year: 2021,
    category: "economy",
    unitsInFleet: 1,
    specs: {
      engineCc: 998,
      seats: 5,
      doors: 4,
      luggage: 2,
      transmission: "manual",
      fuelType: "petrol",
      mileageCityKmpl: 14,
      mileageHighwayKmpl: 18,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 7000,
      withoutFuelDaily: 5000,
      outOfCityDaily: 8500,
      perKm: 28,
      overtimePerHour: 400,
      driverAllowance: 1500,
      nightStayCharge: 1500,
      securityDeposit: 20000,
    },
    colors: [
      { name: "Pearl White", hex: "#F1F2F2" },
      { name: "Silky Silver", hex: "#B3B6BA" },
    ],
    images: [],
    features: [
      "Air conditioning",
      "Power steering",
      "Airbags",
      "Tall cabin",
    ],
    model3d: null,
    availableForCorporate: false,
    isFeatured: false,
  },
  {
    id: "v-suzuki-xbee",
    slug: "suzuki-xbee",
    make: "Suzuki",
    model: "XBEE",
    variant: "Hybrid MZ",
    year: 2018,
    category: "economy",
    unitsInFleet: 1,
    specs: {
      engineCc: 996,
      seats: 5,
      doors: 5,
      luggage: 2,
      transmission: "automatic",
      fuelType: "hybrid",
      mileageCityKmpl: 15,
      mileageHighwayKmpl: 19,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 8000,
      withoutFuelDaily: 6000,
      outOfCityDaily: 10000,
      perKm: 32,
      overtimePerHour: 450,
      driverAllowance: 1500,
      nightStayCharge: 1500,
      securityDeposit: 25000,
    },
    colors: [
      { name: "Pure White Pearl", hex: "#F3F4F4" },
      { name: "Active Yellow", hex: "#E8B23A" },
    ],
    images: [],
    features: [
      "Mild hybrid",
      "Automatic climate control",
      "Rear camera",
      "Compact footprint",
    ],
    model3d: null,
    availableForCorporate: false,
    isFeatured: false,
  },
  {
    id: "v-daihatsu-copen-robe",
    slug: "daihatsu-copen-robe",
    make: "Daihatsu",
    model: "Copen",
    variant: "Robe",
    year: 2014,
    category: "convertible",
    unitsInFleet: 1,
    specs: {
      engineCc: 658,
      seats: 2,
      doors: 2,
      luggage: 1,
      transmission: "automatic",
      fuelType: "petrol",
      mileageCityKmpl: 16,
      mileageHighwayKmpl: 20,
      airConditioning: true,
    },
    rates: {
      withFuelDaily: 25000,
      withoutFuelDaily: 20000,
      outOfCityDaily: 28000,
      perKm: 80,
      overtimePerHour: 1500,
      driverAllowance: 2000,
      nightStayCharge: 2000,
      securityDeposit: 80000,
    },
    colors: [
      { name: "Pearl White", hex: "#F3F4F4" },
      { name: "Red", hex: "#B32A22" },
    ],
    images: [],
    features: [
      "Retractable hard top",
      "Two seats",
      "Event and photography use",
      "Automatic",
    ],
    model3d: null,
    availableForCorporate: false,
    isFeatured: false,
  },
];

export const fuelRates: FuelRates = {
  petrol: 396.65,
  diesel: 395.85,
  // Hi-octane is still a placeholder; the others are the published rates for
  // the date below.
  hiOctane: 425.0,
  effectiveFrom: "2026-10-08",
  note: "Seed values. The office updates these from the admin whenever the notified rates change.",
};

/**
 * Published petrol prices, most recent first. Diesel and hi-octane are only
 * recorded for the current revision; older rows show a dash rather than a
 * number nobody checked.
 */
export const fuelHistory: FuelRateRecord[] = [
  { effectiveFrom: "2026-10-08", petrol: 396.65, diesel: 395.85, hiOctane: 425.0 },
  { effectiveFrom: "2026-10-07", petrol: 394.83, diesel: null, hiOctane: null },
  { effectiveFrom: "2026-10-06", petrol: 393.64, diesel: null, hiOctane: null },
  { effectiveFrom: "2026-10-03", petrol: 392.76, diesel: null, hiOctane: null },
  { effectiveFrom: "2026-10-02", petrol: 390.66, diesel: null, hiOctane: null },
  { effectiveFrom: "2026-10-01", petrol: 387.4, diesel: null, hiOctane: null },
];

export const pricingRules: PricingRules = {
  marginPercent: 10,
  withoutFuelAdjustPercent: 0,
  defaultDriverAllowance: 1500,
  nightStayCharge: 1500,
  chargeReturnLegFuel: true,
  includedKmPerDay: 100,
  roundToNearest: 100,
};

export const routes: Route[] = [
  { origin: "Lahore", destination: "Islamabad", distanceKm: 375, estimatedHours: 4.5, tollCharges: 1200 },
  { origin: "Lahore", destination: "Multan", distanceKm: 350, estimatedHours: 4, tollCharges: 1100 },
  { origin: "Lahore", destination: "Faisalabad", distanceKm: 185, estimatedHours: 2.5, tollCharges: 600 },
  { origin: "Lahore", destination: "Karachi", distanceKm: 1210, estimatedHours: 16, tollCharges: 3500 },
  { origin: "Lahore", destination: "Murree", distanceKm: 410, estimatedHours: 5.5, tollCharges: 1400 },
  { origin: "Islamabad", destination: "Murree", distanceKm: 60, estimatedHours: 1.5, tollCharges: 200 },
  { origin: "Islamabad", destination: "Peshawar", distanceKm: 185, estimatedHours: 2, tollCharges: 500 },
  { origin: "Islamabad", destination: "Naran", distanceKm: 270, estimatedHours: 7, tollCharges: 400 },
  { origin: "Karachi", destination: "Hyderabad", distanceKm: 165, estimatedHours: 2, tollCharges: 400 },
];

export const services: Service[] = [
  {
    id: "s-daily",
    slug: "daily-rental",
    title: "Daily Rental",
    summary:
      "Any vehicle in the fleet by the day, with or without a driver, inside the city or on the road.",
    icon: "calendar",
  },
  {
    id: "s-corporate",
    slug: "corporate-fleet",
    title: "Corporate Fleet Leasing",
    summary:
      "Long-term contracts with vetted drivers, scheduled maintenance and a replacement vehicle guarantee.",
    icon: "briefcase",
  },
  {
    id: "s-airport",
    slug: "airport-transfer",
    title: "Airport Transfer",
    summary:
      "Fixed-price pick-up and drop-off with flight tracking, so a delayed landing costs nothing extra.",
    icon: "plane",
  },
  {
    id: "s-intercity",
    slug: "intercity-travel",
    title: "Intercity Travel",
    summary:
      "Point-to-point journeys priced on distance and the day's fuel rate, quoted before you commit.",
    icon: "route",
  },
  {
    id: "s-events",
    slug: "wedding-and-events",
    title: "Wedding and Events",
    summary: "Presentation-ready vehicles with experienced drivers for events.",
    icon: "sparkles",
  },
  {
    id: "s-staff",
    slug: "staff-transport",
    title: "Staff Transport",
    summary:
      "Scheduled pick and drop for teams, billed monthly against a single invoice.",
    icon: "users",
  },
];

export const faqs: Faq[] = [
  {
    id: "f-documents",
    question: "What documents do I need to rent a car?",
    answer:
      "A valid CNIC and a driving licence for self-drive rentals. Corporate accounts are opened against company registration documents. Exact requirements are confirmed at booking.",
  },
  {
    id: "f-fuel",
    question: "What is the difference between the with-fuel and without-fuel rate?",
    answer:
      "The with-fuel rate includes the fuel for your trip, calculated from the distance, the vehicle's consumption and the day's fuel price. The without-fuel rate covers the vehicle alone and you fill it yourself.",
  },
  {
    id: "f-estimate",
    question: "Why does the fare estimate change from day to day?",
    answer:
      "Fuel prices in Pakistan are revised regularly. Every with-fuel quote is calculated against the current rate, which is published on our fuel prices page along with the date it took effect.",
  },
  {
    id: "f-driver",
    question: "Can I rent without a driver?",
    answer:
      "Yes. Self-drive is available on most of the fleet, subject to documents and a security deposit. Some premium vehicles are chauffeur-driven only.",
  },
  {
    id: "f-cities",
    question: "Which cities do you operate in?",
    answer:
      "Vehicles can be collected in our listed pick-up cities, and out-of-station travel is available nationwide.",
  },
];

/**
 * Testimonials are intentionally empty.
 *
 * Only genuine reviews are published. Fabricated reviews carry a Google policy
 * penalty that removes the entire site from search results, which would defeat
 * the purpose of the build. The components are ready and the section appears as
 * soon as real reviews are supplied.
 */
export const testimonials: Testimonial[] = [];
