#!/usr/bin/env node
/**
 * Turns a list of chosen Sketchfab links into the site's 3D model records.
 *
 * Reads assets/data/sketchfab-models.json, which maps a vehicle slug to either
 * a Sketchfab URL or a bare model UID, fetches each model's real title, author
 * and licence from the API, and writes apps/web/src/lib/cms/models3d.ts.
 *
 * The licence and author are fetched rather than typed in because nearly every
 * Sketchfab model requires its author to be credited, and a credit copied by
 * hand is a credit that eventually goes wrong.
 *
 *   node scripts/sketchfab-apply.mjs
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const inputPath = path.join(root, "assets/data/sketchfab-models.json");
const outputPath = path.join(root, "apps/web/src/lib/cms/models3d.ts");

/** Accepts a full Sketchfab URL or a bare 32-character UID. */
function extractUid(value) {
  const trimmed = value.trim();
  if (/^[0-9a-f]{32}$/i.test(trimmed)) return trimmed;
  const match = trimmed.match(/([0-9a-f]{32})/i);
  if (!match) throw new Error(`Could not find a model id in "${value}"`);
  return match[1];
}

async function fetchModel(uid) {
  const response = await fetch(`https://api.sketchfab.com/v3/models/${uid}`, {
    headers: { Accept: "application/json" },
    signal: AbortSignal.timeout(20000),
  });
  if (!response.ok) {
    throw new Error(`Sketchfab returned ${response.status} for ${uid}`);
  }
  return response.json();
}

function quote(value) {
  return JSON.stringify(String(value ?? ""));
}

async function main() {
  const raw = JSON.parse(await readFile(inputPath, "utf8"));
  const entries = Object.entries(raw).filter(
    ([slug, value]) => !slug.startsWith("_") && typeof value === "object" && value.url,
  );

  if (entries.length === 0) {
    console.log("No models listed yet. Add entries to assets/data/sketchfab-models.json.");
    return;
  }

  const records = [];
  for (const [slug, entry] of entries) {
    const uid = extractUid(entry.url);
    const model = await fetchModel(uid);

    if (model.isDownloadable === undefined && !model.embedUrl) {
      console.warn(`  ${slug}: no embed URL reported; check the model is public`);
    }

    records.push({
      slug,
      uid,
      title: model.name ?? "3D model",
      authorName: model.user?.displayName ?? model.user?.username ?? "Unknown",
      authorUrl: model.user?.profileUrl ?? `https://sketchfab.com/${model.user?.username ?? ""}`,
      modelUrl: model.viewerUrl ?? `https://sketchfab.com/3d-models/${uid}`,
      license: model.license?.label ?? "see model page",
      accuracy: entry.accuracy === "exact" ? "exact" : "representative",
    });

    console.log(`${slug.padEnd(26)} ${model.name}`);
  }

  const body = records
    .map(
      (record) => `  ${quote(record.slug)}: {
    uid: ${quote(record.uid)},
    title: ${quote(record.title)},
    authorName: ${quote(record.authorName)},
    authorUrl: ${quote(record.authorUrl)},
    modelUrl: ${quote(record.modelUrl)},
    license: ${quote(record.license)},
    accuracy: ${quote(record.accuracy)},
  },`,
    )
    .join("\n");

  const file = `import type { SketchfabModel } from "./types";

/**
 * Sketchfab models, keyed by vehicle slug.
 *
 * Generated by \`npm run sketchfab:apply\` from the links in
 * assets/data/sketchfab-models.json. Titles, authors and licences come from
 * the Sketchfab API rather than being typed in, so the credit shown on the
 * site always matches the model's own record.
 *
 * A vehicle missing from this map simply shows its photographs instead.
 */
export const models3d: Record<string, SketchfabModel> = {
${body}
};
`;

  await writeFile(outputPath, file, "utf8");
  console.log(`\nWritten ${records.length} models to ${path.relative(root, outputPath)}`);
}

await main();
